PUT http://localhost:3003/api/categories/641af51f85474a468ef03f7c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2hpdGEiLCJpZCI6IjY0MWM2MzdiMDY0OGM4Nzg1MzIxN2QxNiIsImlhdCI6MTY3OTYwNTgyM30.UXW-NDl7QHaJ3GR81Ph6drgo9_3RtQyuNo4mzUd_D7E

{
  "category_name": "Food"
}
